### ISSUE TITLE
Occasional null block when querying the blockchain

### ISSUE THREAD

**Issue by nickmelis** [ethereum/ethereumj#419] opened 2016-06-14 10:12 UTC
Using Ethereum 1.2.7-SNAPSHOT connected to Morden.

I have created a custom EthereumListener and implemented the onBlock() method.
Inside the onBlock() method I call Ethereum.getBlockchain().getBlockByNumber() with the block number passed down the listener.
Sometimes what I get from Ethereum.getBlockchain().getBlockByNumber() is null. It happens randomly so I am not sure what's causing it

**Comment by Nashatyrev** [comment] 2016-06-14 11:44
@nickmelis wrote:  I am running with 1.2.7-RELEASE and still getting the same problem

So you are getting `null` blocks on new blocks or blocks which were imported with the previous version?

**Comment by nickmelis** [comment] 2016-06-14 13:03
Hi Anton,
I am getting null on new blocks. I call Ethereum.getBlockchain().getBlockByNumber() inside the listener methd onBlock(), so as soon as my client receives the block. Running on 1.2.7-SNAPSHOT now and still seeing the error.

**Comment by Nashatyrev** [comment] 2016-06-14 13:10
Hm... This might be another issue: when a forked block arrives we are calling listener before `rebranch` operation, this could be the reason. 
Can you please try the following workaround: process `onBlock` event on a parallel thread with some timeout (like 200-1000ms)?

**Comment by nickmelis** [comment] 2016-06-14 13:11
If it was a forked block, would onBlock() get called twice with the same block number?

**Comment by Nashatyrev** [comment] 2016-06-14 13:19
Yes, but those blocks should have different hashes

**Comment by nickmelis** [comment] 2016-06-14 13:21
I am afraid this may not be the case then...I log every block number that goes through the onBlock() listener method. If it was a rebranch, I would see the same block number logged twice, am I right?

**Comment by Nashatyrev** [comment] 2016-06-14 13:49
@nickmelis Ok, I'll try to reproduce the case. How frequent does `null` appears?

**Comment by Nashatyrev** [comment] 2016-06-14 13:53
BTW, can you try the same with the `develop` version? We are going to promote it to RELEASE this week

**Comment by nickmelis** [comment] 2016-06-14 13:59
Just put a note on the first comment. I am using 1.2.7-SNAPSHOT. It appears to occur every 30-50 blocks, but it's quite random. It's happened twice in a row with block 1132820 and 1132821

**Comment by Nashatyrev** [comment] 2016-06-14 14:06
Are you working with Morden?

**Comment by nickmelis** [comment] 2016-06-14 14:10
Yes I am.

**Comment by nickmelis** [comment] 2016-06-14 14:17
This is my listener: 
`
private final EthereumListener listener = new EthereumListenerAdapter() {
    @Override
    public void onBlock(Block block, List<TransactionReceipt> receipts) {
      if (ethereum.getBlockchain().getBlockByNumber(block.getNumber()) == null) {
        logger.error("Block {} was null", block.getNumber());
      } 
    }
  };
`

**Comment by Nashatyrev** [comment] 2016-06-14 23:38
@nickmelis Reproduced this issue. This indeed happens on rebranch and can be workarounded by calling `getBlockByNumber` in a separate thread. 
Will be fixed shortly

**Comment by nickmelis** [comment] 2016-06-15 10:53
@Nashatyrev do you have a rough ETA for when the fix will be in develop?

**Comment by Nashatyrev** [comment] 2016-06-15 23:03
@nickmelis Looking forward to push the fix tomorrow

**Closed** 2016-06-16 10:50 UTC
