### ISSUE TITLE
FastSyncManager isn't closed properly when exception happened during Spring Boot start

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#634] opened 2016-12-16 15:38 UTC
I launched Harmony `develop`  with:
`./gradlew clean bootRun -Dlogs.keepStdOut=true -Dsync.fast.enabled=true -Dserver.ssl.key-store=123 -Ddatabase.dir=123`

As result context closed, but FastSyncManager continues to operate.
```

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.

2016-12-16 17:35:54,824 INFO  [restartedMain] facade - ### Shutdown initiated ### 
2016-12-16 17:35:54,824 INFO  [restartedMain] facade - Shutting down Ethereum instance...
2016-12-16 17:35:54,824 INFO  [restartedMain] general - close: stopping peer discovery ...
2016-12-16 17:35:54,832 INFO  [restartedMain] general - close: stopping ChannelManager ...
2016-12-16 17:35:54,834 INFO  [restartedMain] general - close: stopping SyncManager ...
2016-12-16 17:35:56,628 INFO  [FastSyncLoop] sync - FastSync: waiting for at least 5 peers or 54 sec to select pivot block... (0 peers so far)
```

**Comment by zilm13** [comment] 2016-12-16 15:42
This bug should be fixed by https://github.com/ethereum/ethereumj/commit/dfe0234c2674856840fdad129e76afd5a6a33dca
I will notify you when it's merged in develop

**Comment by zilm13** [comment] 2016-12-16 15:44
@cupuyc ahh looks like this part is not covered. I will add it.

**Comment by zilm13** [comment] 2016-12-20 09:17
Should be fixed by https://github.com/ethereum/ethereumj/commit/e358c0b13c84a92100a0d5e9ae5a7ccd16d983fa

**Comment by zilm13** [comment] 2016-12-21 12:18
@cupuyc check with latest develop

**Comment by Nashatyrev** [comment] 2016-12-22 15:03
Closing this. Please reopen if still reproducible

**Closed by Nashatyrev** 2016-12-22 15:03 UTC
