### ISSUE TITLE
peer to peer 

### ISSUE THREAD

**Issue by 3Mohammed2013** [ethereum/ethereumj#1045] opened 2018-03-30 11:31 UTC
I am new users of the Ethereumj , and I don't know excitedly I have a couple of a question 
1 how can we connect peer to peer on Ethereumj 
2- the wallet that appears on the ethereum-harmary where come from

**Comment by zilm13** [comment] 2018-05-27 22:27
Duplicate of similar thread in Harmony issues

**Closed by zilm13** 2018-05-27 22:27 UTC
