### ISSUE TITLE
Replace `Hex.toHexString` in logging, toString etc to safer alternative in Tests

### ISSUE THREAD

**Issue by kishansagathiya** [ethereum/ethereumj#1081] opened 2018-05-23 04:47 UTC
Whatever was done in https://github.com/ethereum/ethereumj/pull/1069, We might require a similar exercise in tests as well

**Comment by zilm13** [comment] 2018-05-23 08:19
@kishansagathiya I don't think it's required. We need it in app, because complete logging is useful to find strange bugs when you have not reproducible report + on some logging levels new errors occur due to lack of safety in logging. When strange values appears in test, it's reproducible and it's a sign that test should be fixed.

**Closed by zilm13** 2018-05-23 08:19 UTC
